const productView = [
 {
   id: 1,
   photo: 'WatchPhoto',
   name: 'Apple Watch',
   model: 'Series 5 SE',
   rating: 5,
   price: 529.99,
   description: 'Lorem ipsum',
   details: 'Lorem ipsum',
 },
 {
   id: 2,
   photo: 'Headphones',
   name: 'Sony ZX330BT',
   model: 'Light Grey',
   rating: 5,
   price: 39.99,
   description: 'Lorem ipsum',
   details: 'Lorem ipsum',
 },
 {
   id: 3,
   photo: 'Iphone13',
   name: 'iPhone 13',
   model: 'Navy Blue',
   rating: 5,
   price: 729.99,
   description: 'Lorem ipsum',
   details: 'Lorem ipsum',
 },
 {
   id: 4,
   photo: 'Iphone13Pro',
   name: 'iPhone 13 Pro',
   model: 'Grey',
   rating: 5,
   price: 819.99,
   description: 'Lorem ipsum',
   details: 'Lorem ipsum',
 },
 {
   id: 5,
   photo: 'iPhone12SubwayBlue',
   name: 'iPhone 12',
   model: 'Subway Blue',
   rating: 5,
   price: 619.99,
   description: 'Lorem ipsum',
   details: 'Lorem ipsum',
 },
 {
   id: 6,
   photo: 'iPhone11Red',
   name: 'iPhone 11 Red',
   model: 'Lilac Purple',
   rating: 5,
   price: 849.99,
   description: 'Lorem ipsum',
   details: 'Lorem ipsum',
 },
 {
   id: 7,
   photo: 'iPhone12White',
   name: 'iPhone 12 White',
   model: 'Product RED',
   rating: 5,
   price: 3249.99,
   description: 'Lorem ipsum',
   details: 'Lorem ipsum',
 },
 {
   id: 8,
   photo: 'Samsung21',
   name: 'Samsung Galaxy S21+',
   model: 'Milky White',
   rating: 5,
   price: 619.99,
   description: 'Lorem ipsum',
   details: 'Lorem ipsum',
 },
 {
   id: 9,
   photo: 'samsungNote21',
   name: 'Samsung Galaxy Note',
   model: '2 - Options',
   rating: 5,
   price: 999.99,
   description: 'Lorem ipsum',
   details: 'Lorem ipsum',
 },
 {
   id: 10,
   photo: 'Iphone11black',
   name: 'iPhone 11',
   model: 'Serious Black',
   rating: 5,
   price: 696.99,
   description: 'Lorem ipsum',
   details: 'Lorem ipsum',
 },
];
